### ISSUE TITLE
Can not install on latest blitz.js

### ISSUE THREAD

**Issue by Zxilly** [ntgussoni/blitz-guard-recipe#7]
### What is the problem?
@ntgussoni I failed to install blitz-guard on latest blitz.js.

When I want to install it, I got 

```log
PS C:\Projects\CS_Projects\2021\blitz-test-shield> blitz install ntgussoni/blitz-guard-recipe
✅ Installed 1 dependency
✅ Successfully created app\guard\queries\getAbility.ts
✅ Successfully created app\guard\ability.ts

+––––––––––––––––––––––––––––––––+
⎪   Add development middleware   ⎪
+––––––––––––––––––––––––––––––––+
Do you wish to add the development middleware to help you detect unprotected endpoints?

C:\Projects\CS_Projects\2021\blitz-test-shield\.blitz\recipe-install\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

Error: At least one choice must be selectable
    at AutoComplete.reset (C:\Projects\CS_Projects\2021\blitz-test-shield\.blitz\recipe-install\node_modules\enquirer\lib\types\array.js:38:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async AutoComplete.initialize (C:\Projects\CS_Projects\2021\blitz-test-shield\.blitz\recipe-install\node_modules\enquirer\lib\types\array.js:25:5)
    at async C:\Projects\CS_Projects\2021\blitz-test-shield\.blitz\recipe-install\node_modules\enquirer\lib\prompt.js:236:7

```

### Steps to Reproduce

1. execute `blitz install ntgussoni/blitz-guard-recipe`

### Versions

```log
PS C:\Projects\CS_Projects\2021\blitz-test-shield> blitz --version --verbose
debug: blitzPkgPath: C:\Projects\CS_Projects\2021\blitz-test-shield\node_modules\blitz\dist\blitz.cjs.js
debug: cliPkgPath: C:\Projects\CS_Projects\2021\blitz-test-shield\node_modules\@blitzjs\cli\lib\src\index.js

Windows 10 | win32-x64 | Node: v16.5.0

blitz: 0.38.6 (local)

  Package manager: yarn
  System:
    OS: Windows 10 10.0.19043
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
    Memory: 3.61 GB / 15.37 GB
  Binaries:
    Node: 16.5.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.19.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/client: 2.27.0 => 2.27.0
    blitz: 0.38.6 => 0.38.6
    prisma: 2.27.0 => 2.27.0
    react: alpha => 18.0.0-alpha-419cc9c37-20210726
    react-dom: alpha => 18.0.0-alpha-419cc9c37-20210726
    typescript: ~4.3 => 4.3.5
```

**Comment by ntgussoni** [comment]
Yes, that's because blitz started to use .ts config file and we cannot (yet) add the middleware to it.

However, that's the only missing step. You can add it manually in 1 minute, following this.
https://ntgussoni.github.io/blitz-guard/docs/middleware

Thanks for reporting! Ill try to get it fixed asap
